### ISSUE TITLE
`mix test` failed due to test for `create_publisher/3`

### ISSUE THREAD

**Issue by takasehideki** [rclex/rclex#216]
When PR #215 was created, the following error occurred in CI test.
https://github.com/rclex/rclex/actions/runs/3699448637/jobs/6266827488

```
Compiling 24 files (.ex)
Generated rclex app
.....................................................................

  1) test create_publisher/3 return {:ok, publisher_id} (Rclex.NodeTest)
     test/rclex/node_test.exs:44
     ** (RuntimeError) failed to start child with the spec {Rclex.Node, {#Reference<0.2087098984.2588540930.66134>, 'node_b1', {1, #Function<12.53267529/1 in Rclex.NodeTest.__ex_unit_setup_0/1>}}}.
     Reason: shutdown: failed to start child: Rclex.JobQueue
         ** (EXIT) already started: #PID<0.[303](https://github.com/rclex/rclex/actions/runs/3699448637/jobs/6266827488#step:8:304)1.0>
     stacktrace:
       (ex_unit 1.13.4) lib/ex_unit/callbacks.ex:433: ExUnit.Callbacks.start_supervised!/2
       test/rclex/node_test.exs:25: anonymous fn/3 in Rclex.NodeTest.__ex_unit_setup_0/1
       (elixir 1.13.4) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
       test/rclex/node_test.exs:23: Rclex.NodeTest.__ex_unit_setup_0/1
       test/rclex/node_test.exs:1: Rclex.NodeTest.__ex_unit__/2

     The following output was logged:
     
     23:03:22.470 [debug] JobExecutor start
     
     23:03:22.470 [debug] JobExecutor start
     
.....................................................................*....

Finished in 0.8 seconds (0.00s async, 0.8s sync)
144 tests, 1 failure, 1 skipped

Randomized with seed 613759
Error: Process completed with exit code 2.
```

<img width="1357" alt="image" src="https://user-images.githubusercontent.com/23649012/207749043-c032a717-d846-46a5-986f-9490ad378335.png">

Here is the test code for the above error.
https://github.com/rclex/rclex/blob/main/test/rclex/node_test.exs#L43-L53

```
  describe "create_publisher/3" do
    test "return {:ok, publisher_id}", %{node_id: node_id, msg_type: msg_type, topic: topic} do
      publisher_id = {node_id, topic, :pub}

      try do
        assert {:ok, ^publisher_id} = Node.create_publisher(node_id, msg_type, topic)
      after
        Node.finish_job(publisher_id)
      end
    end
  end
```

**Comment by takasehideki** [comment]
This error did not occur when re-running CI test. So I guess the cause may depend on the timing.
